version: '3.7'

services:
  laravel:
    build:
      context: '.'
    container_name: laravel
    env_file: dotenv/docker.env
    ports:
      - 8000:80
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    depends_on:
      - mysql
      - mailhog
    # volumes:
      #   - .:/var/www/html

  mysql:
    image: "mysql:8.0.18"
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"

  mailhog:
    image: mailhog/mailhog
    expose:
      - 1025
      - 8025
    ports:
      - 1025:1025
      - 8025:8025
